// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Context;

public partial class T_Cliente
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int? Dni { get; set; }

    public int? Telefono { get; set; }

    public DateOnly? Fecha_nac { get; set; }

    public string ObraSocial { get; set; }

    public virtual ICollection<T_Venta> Ventas { get; set; } = new List<T_Venta>();
}