// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Context;

public partial class T_Detalles_Venta
{
    public int Id { get; set; }

    public int? NroDetalle { get; set; }

    public string Producto { get; set; }

    public decimal? Precio { get; set; }

    public int? Cantidad { get; set; }

    public decimal? TotalDetalle { get; set; }

    public int? cod_venta { get; set; }

    public virtual T_Venta cod_ventaNavigation { get; set; }
}