// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Context;

public partial class T_User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Contraseña { get; set; }
}