// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Context;

public partial class T_Venta
{
    public int Id { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? cod_cliente { get; set; }

    public decimal? TotalVenta { get; set; }

    public virtual ICollection<T_Detalles_Venta> Detalles { get; set; } = new List<T_Detalles_Venta>();

    public virtual T_Cliente cod_clienteNavigation { get; set; }
}