// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class TCliente
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int Dni { get; set; }

    public string Email { get; set; }

    public int? Tel { get; set; }

    public DateOnly? FechaNac { get; set; }

    public string ObraSocial { get; set; }
}